LottoGO/LottoGO.AdminPanel/Controllers/BonusesController.cs
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using LottoGO.AdminPanel.Models;
using LottoGO.AdminPanel.Models.DataTables;
using LottoGO.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LottoGO.AdminPanel.Controllers
{
	public class BonusesController : BaseController
	{
		private readonly LottoGoDbContext _context;

		public BonusesController(LottoGoDbContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			return View();
		}

		public async Task<IActionResult> Add()
		{
			var availablePoints = await _context.MapPoints.Where(p => p.ExtraPrize == decimal.Zero && p.IsActive).ToListAsync();
			var bonusVm = new BonusViewModel()
			{
				AvailableMapPoints = availablePoints.Select(p => new MapPoint()
				{
					Id = p.Id,
					Name = p.Name
				})
			};

			return View(bonusVm);
		}

		[HttpPost]
		public async Task<IActionResult> Add(BonusViewModel bonusViewModel)
		{
			if (ModelState.IsValid)
			{
				var mapPoint = await _context.MapPoints.FindAsync(bonusViewModel.SelectedMapPoint);
				mapPoint.ExtraPrize = bonusViewModel.ExtraPrize;
				_context.Entry(mapPoint).State = EntityState.Modified;
				await _context.SaveChangesAsync();
				return RedirectToAction("Index");
			}

			return View(bonusViewModel);
		}

		[HttpDelete]
		public async Task<IActionResult> DeleteBonus(int mapPointId)
		{
			var mapPoint = await _context.MapPoints.FindAsync(mapPointId);
			mapPoint.ExtraPrize = 0;
			_context.Entry(mapPoint).State = EntityState.Modified;
			await _context.SaveChangesAsync();

			return CreateServerResponse(string.Empty, HttpStatusCode.OK);
		}

		public async Task<IActionResult> GetBonuses(int draw, int start, int length)
		{
			var pointsCount = await _context.MapPoints.CountAsync(p => p.ExtraPrize != decimal.Zero);
			var points = await _context.MapPoints.Where(p => p.ExtraPrize != decimal.Zero).Skip(start).Take(length).ToListAsync();

			return CreateServerResponse(new BonusesTableModel()
			{
				Data = points.Select(u => new BonusTableModel()
				{
					Id = u.Id,
					Name = u.Name,
					ExtraPrize = $"{u.ExtraPrize} PLN"
				}).ToList(),
				Draw = draw,
				RecordsFiltered = pointsCount,
				RecordsTotal = pointsCount
			}, HttpStatusCode.OK);
		}
	}
}

LottoGO/LottoGO.AdminPanel/Controllers/PointsController.cs
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using LottoGO.AdminPanel.Models;
using LottoGO.AdminPanel.Models.DataTables;
using LottoGO.Database;
using LottoGO.Database.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;

namespace LottoGO.AdminPanel.Controllers
{
    public class PointsController : BaseController
    {
	    private readonly LottoGoDbContext _context;
	    private readonly ILogger<PointsController> _logger;
	    private readonly IStringLocalizer<PointsController> _stringLocalizer;

	    public PointsController(LottoGoDbContext context, ILogger<PointsController> logger, IStringLocalizer<PointsController> stringLocalizer)
	    {
		    _context = context;
		    _logger = logger;
		    _stringLocalizer = stringLocalizer;
	    }

        public IActionResult Index()
        {
            return View();
        }

	    public async Task<IActionResult> Edit(int mapPointId)
	    {
		    var mapPoint = await  _context.MapPoints.FindAsync(mapPointId);
		    return View("Add", new PointViewModel()
		    {
				ExtraPrize = mapPoint.ExtraPrize,
				GameType = (GameType)mapPoint.GameType,
				StandardPrize = mapPoint.StandardPrize,
				Latitude = mapPoint.Latitude,
				Longitude = mapPoint.Longitude,
				MarkerId = mapPoint.MarkerId,
				Name = mapPoint.Name,
				GameCost = mapPoint.SingleGameCost,
				Id = mapPoint.Id,
				MarkersIds = mapPoint.MultipleMarkers
		    });
	    }

		public async Task<IActionResult> GetPoints(int draw, int start, int length)
	    {
		    var pointsCount = await _context.MapPoints.CountAsync(p=>p.IsActive);
		    var points = await _context.MapPoints.Where(p=>p.IsActive).Skip(start).Take(length).ToListAsync();

		    return CreateServerResponse(new PointsTableModel()
		    {
			    Data = points.Select(u => new PointTableModel()
			    {
				    Id = u.Id,
					Longitude = u.Longitude,
					Name = u.Name,
					Latitude = u.Latitude,
					GameCost = $"{u.SingleGameCost} PLN",
					StandardPrize = $"{u.StandardPrize} PLN",
				    ExtraPrize = $"{u.ExtraPrize} PLN",
					GameType = _stringLocalizer[((GameType)u.GameType).ToString()],
					MarkerId = u.MarkerId
				}).ToList(),
			    Draw = draw,
			    RecordsFiltered = pointsCount,
			    RecordsTotal = pointsCount
		    }, HttpStatusCode.OK);
	    }

		[HttpPost]
	    public async Task<IActionResult> Add(PointViewModel viewModel)
	    {
		    try
		    {
			    if (ModelState.IsValid)
			    {
				    var mapPointEntity = new MapPoints
				    {
					    Latitude = viewModel.Latitude.Value,
					    Longitude = viewModel.Longitude.Value,
					    GameType = (int) viewModel.GameType,
					    SingleGameCost = viewModel.GameCost,
					    MarkerId = viewModel.MarkerId,
					    Name = viewModel.Name,
					    StandardPrize = viewModel.StandardPrize,
						MultipleMarkers = viewModel.MarkersIds,
						IsActive = true
				    };
				    _context.Entry(mapPointEntity).State = EntityState.Added;
				    await _context.SaveChangesAsync();
				    return RedirectToAction("Index");
			    }

			    return View(viewModel);
		    }
		    catch (Exception e)
		    {
			    _logger.LogError(e.ToString());
			    return View(viewModel);
		    }
	    }

	    [HttpPost]
	    public async Task<IActionResult> Edit(PointViewModel viewModel)
	    {
		    try
		    {
			    if (ModelState.IsValid)
			    {
				    var mapPoint = await _context.MapPoints.FindAsync(viewModel.Id);

				    mapPoint.Latitude = viewModel.Latitude.Value;
				    mapPoint.Longitude = viewModel.Longitude.Value;
				    mapPoint.GameType = (int) viewModel.GameType;
				    mapPoint.SingleGameCost = viewModel.GameCost;
				    mapPoint.MarkerId = viewModel.MarkerId;
				    mapPoint.MultipleMarkers = viewModel.MarkersIds;
				    mapPoint.Name = viewModel.Name;
				    mapPoint.StandardPrize = viewModel.StandardPrize;

				    _context.Entry(mapPoint).State = EntityState.Modified;
				    await _context.SaveChangesAsync();
				    return RedirectToAction("Index");
			    }

			    return View("Add", viewModel);
		    }
		    catch (Exception e)
		    {
			    _logger.LogError(e.ToString());
			    return View("Add", viewModel);
		    }
	    }


	    [HttpDelete]
	    public async Task<IActionResult> DeletePoint(int mapPointId)
	    {
		    var mapPoint = await _context.MapPoints.FindAsync(mapPointId);
		    mapPoint.IsActive = false;
		    _context.Entry(mapPoint).State = EntityState.Modified;
		    await _context.SaveChangesAsync();

		    return CreateServerResponse(string.Empty, HttpStatusCode.OK);
	    }

		public IActionResult Add()
	    {
		    return View();
	    }
    }
}

LottoGO/LottoGO.AdminPanel/Controllers/UsersController.cs
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LottoGO.AdminPanel.Models;
using LottoGO.AdminPanel.Models.DataTables;
using LottoGO.Database;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace LottoGO.AdminPanel.Controllers
{
	[Authorize]
	public class UsersController : BaseController
	{
		private readonly LottoGoDbContext _context;

		public UsersController(LottoGoDbContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			return View();
		}

		public async Task<IActionResult> GetUsers(int draw, int start, int length)
		{
			var usersCount = await _context.Users.CountAsync(u => u.UserName != "admin" && u.IsActive);
			var users = await _context.Users.Where(u => u.UserName != "admin" && u.IsActive).Skip(start).Take(length).ToListAsync();

			return CreateServerResponse(new UsersTableModel
			{
				Data = users.Select(u => new UserModel()
				{
					Id = u.Id,
					AccountBalance = $"{u.AccountBalance} PLN",
					Username = u.UserName,
					Email = u.Email
				}).ToList(),
				Draw = draw,
				RecordsFiltered = usersCount,
				RecordsTotal = usersCount
			}, HttpStatusCode.OK);
		}

		[HttpDelete]
		public async Task<IActionResult> DeleteUser(string userId)
		{
			var user = await _context.Users.FindAsync(userId);
			user.IsActive = false;
			_context.Entry(user).State = EntityState.Modified;
			await _context.SaveChangesAsync();

			return CreateServerResponse(string.Empty, HttpStatusCode.OK);
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

LottoGO/LottoGO.AdminPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LottoGO Admin Panel</title>
    <link rel="stylesheet" href="~/css/normalize.css">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <link rel="stylesheet" href="~/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/css/cs-skin-elastic.css">
    <link rel="stylesheet" href="~/scss/style.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" />
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

</head>

<body class="bg-dark">
    @if (!string.IsNullOrEmpty(User.Identity.Name))
    {
        <text>
            <aside id="left-panel" class="left-panel">
                <nav class="navbar navbar-expand-sm navbar-default">

                    <div class="navbar-header">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fa fa-bars"></i>
                        </button>
                        <a class="navbar-brand" href="./"><img src="images/logo.png" alt="Logo"></a>
                        <a class="navbar-brand hidden" href="./"><img src="images/logo2.png" alt="Logo"></a>
                    </div>

                    <div id="main-menu" class="main-menu collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <h3 class="menu-title">Menu</h3><!-- /.menu-title -->
                            <li>
                                <a asp-action="Index" asp-controller="Users"> <i class="menu-icon fa fa-users"></i>@Localizer["Users"] </a>
                                <a asp-action="Index" asp-controller="Points"> <i class="menu-icon fa fa-street-view"></i>@Localizer["Points"] </a>
                                @*<a href="widgets.html"> <i class="menu-icon fa fa-bell"></i>@Localizer["Pushes"] </a>*@
                                <a asp-action="Index" asp-controller="Bonuses"> <i class="menu-icon fa fa-star"></i>@Localizer["Bonuses"] </a>
                            </li>
                            
                            <h3 class="menu-title">@Localizer["User"]</h3><!-- /.menu-title -->
                            <li>
                                <a asp-action="Logout" asp-controller="Account"> <i class="menu-icon fa fa-sign-in"></i>@Localizer["Logout"] </a>
                            </li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
            </aside><!-- /#left-panel -->
            <!-- Left Panel -->
            <!-- Right Panel -->
        
            <div id="right-panel" class="right-panel">

            <!-- Header-->
            <header id="header" class="header">
                <div class="header-menu">
                    <div class="col-sm-7">
                        <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                    </div>
                    
                    <div class="col-sm-5">
                        <div class="user-area dropdown float-right">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img class="user-avatar rounded-circle" src="images/logoblack.png">
                            </a>
                            <div class="user-menu dropdown-menu">
                                <a class="nav-link" asp-controller="Account" asp-action="Logout"><i class="fa fa-power -off"></i>@Localizer["Logout"]</a>
                            </div>
                        </div>
                    </div>
                </div>
            </header><!-- /header -->
        </text>
    }

@RenderBody()
</div>

    <!-- /#right-panel -->
    <!-- Header-->


    <script src="~/js/vendor/jquery-2.1.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    <script src="~/js/plugins.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/lib/chart-js/Chart.bundle.js"></script>
    <script src="~/js/dashboard.js"></script>
    <script src="~/js/widgets.js"></script>
    <script src="~/js/lib/vector-map/jquery.vmap.js"></script>
    <script src="~/js/lib/vector-map/jquery.vmap.min.js"></script>
    <script src="~/js/lib/vector-map/jquery.vmap.sampledata.js"></script>
<script src="~/js/lib/vector-map/country/jquery.vmap.world.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>